In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [4]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [15]:
Teen = df[df['Age'].isin(range(13, 18))]

Teen.shape
Teen['Age'].unique()

array([14., 15., 17., 16., 13.])

In [17]:
Teenage = df[(df['Age'] > 12) & (df['Age'] < 18)]
Teenage.shape
Teenage['Age'].unique()

array([14. , 15. , 17. , 16. , 14.5, 13. ])

In [6]:
Teen.head()

PassengerId  Survived  Pclass                                  Name  \
9            10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
22           23         1       3           McGowan, Miss. Anna "Annie"   
39           40         1       3           Nicola-Yarred, Miss. Jamila   
68           69         1       3       Andersson, Miss. Erna Alexandra   

       Sex   Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
9   female  14.0      1      0   237736  30.0708   NaN        C  
14  female  14.0      0      0   350406   7.8542   NaN        S  
22  female  15.0      0      0   330923   8.0292   NaN        Q  
39  female  14.0      1      0     2651  11.2417   NaN        C  
68  female  17.0      4      2  3101281   7.9250   NaN        S

In [7]:
df['Family Size'] = df['SibSp'] + df['Parch'] + 1
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Family Size  
0      0         A/5 21171   7.2500   NaN        S            2  
1      0          PC 17599  71.2833   C85        C            2  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            2  
4      0            373450   8.0500   NaN        S            1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  Family Size  891 non-null    int64  
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


In [9]:
df['Family Size'].unique()

array([ 2,  1,  5,  3,  7,  6,  4,  8, 11], dtype=int64)

In [10]:
## Converting Categorical Features to Numerical in Pandas
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [11]:
df['Sex'] = df['Sex'].map({'male':0, 'female':1})
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Family Size  
0         A/5 21171   7.2500   NaN        S            2  
1          PC 17599  71.2833   C85        C            2  
2  STON/O2. 3101282   7.9250   NaN        S            1  
3            113803  53.1000  C123        S            2  
4            373450   8.0500   NaN        S            1

In [12]:
df['Survived'] = df['Survived'].map({0:'No', 1:'Yes'})
df.head()

PassengerId Survived  Pclass  \
0            1       No       3   
1            2      Yes       1   
2            3      Yes       3   
3            4      Yes       1   
4            5       No       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Family Size  
0         A/5 21171   7.2500   NaN        S            2  
1          PC 17599  71.2833   C85        C            2  
2  STON/O2. 3101282   7.9250   NaN        S            1  
3            113803  53.1000  C123        S            2  
4            373450   8.0500   NaN        S            1

In [13]:
dff = pd.read_csv('covid_tracking.csv')
dff.head()

date state  positive   negative  pending  hospitalized_currently  \
0  2021-03-07    AK   56886.0        NaN      NaN                    33.0   
1  2021-03-07    AL  499819.0  1931711.0      NaN                   494.0   
2  2021-03-07    AR  324818.0  2480716.0      NaN                   335.0   
3  2021-03-07    AS       0.0     2140.0      NaN                     NaN   
4  2021-03-07    AZ  826454.0  3073010.0      NaN                   963.0   

   hospitalized_cumulative  in_icu_currently  in_icu_cumulative  \
0                   1293.0               NaN                NaN   
1                  45976.0               NaN             2676.0   
2                  14926.0             141.0                NaN   
3                      NaN               NaN                NaN   
4                  57907.0             273.0                NaN   

   on_ventilator_currently  ...  fips  death_increase  hospitalized_increase  \
0                      2.0  ...     2               0                      0   
1                      NaN  ...     1              -1                      0   
2                     65.0  ...     5              22                     11   
3                      NaN  ...    60               0                      0   
4                    143.0  ...     4               5                     44   

  negative_increase positive_increase total_test_results_increase  fips_code  \
0                 0               0.0                           0          2   
1              2087             408.0                        2347          1   
2              3267             165.0                        3380          5   
3                 0               0.0                           0         60   
4             13678            1335.0                       45110          4   

   iso_subdivision            load_time  iso_country  
0            US-AK  2024-11-03 00:03:24           US  
1            US-AL  2024-11-03 00:03:24           US  
2            US-AR  2024-11-03 00:03:24           US  
3            US-AS  2024-11-03 00:03:24           US  
4            US-AZ  2024-11-03 00:03:24           US  

[5 rows x 31 columns]

In [41]:
dff.describe(include = ['object'])

date  state       last_update_et  \
count        22261  22261                21608   
unique         420     56                 9502   
top     2021-03-07     MI  2020-12-01 00:00:00   
freq            60    744                  113   

                                            hash          date_checked  \
count                                      22261                 21608   
unique                                     20780                  9502   
top     fa18cafe4610610baf1bf4c9d2b0288716f72194  2020-12-01T00:00:00Z   
freq                                           2                   113   

       iso_subdivision            load_time iso_country  
count            22261                22261       22261  
unique              57                    1           1  
top              US-UM  2024-11-03 00:03:24          US  
freq              1481                22261       22261

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dff['state_code'] = le.fit_transform(dff['state'])
dff.head()

date state  positive   negative  pending  hospitalized_currently  \
0  2021-03-07    AK   56886.0        NaN      NaN                    33.0   
1  2021-03-07    AL  499819.0  1931711.0      NaN                   494.0   
2  2021-03-07    AR  324818.0  2480716.0      NaN                   335.0   
3  2021-03-07    AS       0.0     2140.0      NaN                     NaN   
4  2021-03-07    AZ  826454.0  3073010.0      NaN                   963.0   

   hospitalized_cumulative  in_icu_currently  in_icu_cumulative  \
0                   1293.0               NaN                NaN   
1                  45976.0               NaN             2676.0   
2                  14926.0             141.0                NaN   
3                      NaN               NaN                NaN   
4                  57907.0             273.0                NaN   

   on_ventilator_currently  ...  death_increase  hospitalized_increase  \
0                      2.0  ...               0                      0   
1                      NaN  ...              -1                      0   
2                     65.0  ...              22                     11   
3                      NaN  ...               0                      0   
4                    143.0  ...               5                     44   

   negative_increase positive_increase total_test_results_increase fips_code  \
0                  0               0.0                           0         2   
1               2087             408.0                        2347         1   
2               3267             165.0                        3380         5   
3                  0               0.0                           0        60   
4              13678            1335.0                       45110         4   

   iso_subdivision            load_time  iso_country  state_code  
0            US-AK  2024-11-03 00:03:24           US           0  
1            US-AL  2024-11-03 00:03:24           US           1  
2            US-AR  2024-11-03 00:03:24           US           2  
3            US-AS  2024-11-03 00:03:24           US           3  
4            US-AZ  2024-11-03 00:03:24           US           4  

[5 rows x 32 columns]

In [71]:
dff.iloc[:, 1]

0        AK
1        AL
2        AR
3        AS
4        AZ
         ..
22256    WA
22257    WA
22258    WA
22259    WA
22260    WA
Name: state, Length: 22261, dtype: object

In [73]:
dff.iloc[:, -1]

0         0
1         1
2         2
3         3
4         4
         ..
22256    52
22257    52
22258    52
22259    52
22260    52
Name: state_code, Length: 22261, dtype: int32

In [75]:
df.head()

PassengerId Survived  Pclass  \
0            1       No       3   
1            2      Yes       1   
2            3      Yes       3   
3            4      Yes       1   
4            5       No       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Family Size  
0         A/5 21171   7.2500   NaN        S            2  
1          PC 17599  71.2833   C85        C            2  
2  STON/O2. 3101282   7.9250   NaN        S            1  
3            113803  53.1000  C123        S            2  
4            373450   8.0500   NaN        S            1

In [77]:
df['Survived_code'] = le.fit_transform(df['Survived'])
df.head()

PassengerId Survived  Pclass  \
0            1       No       3   
1            2      Yes       1   
2            3      Yes       3   
3            4      Yes       1   
4            5       No       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Family Size  Survived_code  
0         A/5 21171   7.2500   NaN        S            2              0  
1          PC 17599  71.2833   C85        C            2              1  
2  STON/O2. 3101282   7.9250   NaN        S            1              1  
3            113803  53.1000  C123        S            2              1  
4            373450   8.0500   NaN        S            1              0

In [27]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [31]:
df.dropna(inplace = True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    object 
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    int64  
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
 12  Family Size  183 non-null    int64  
dtypes: float64(2), int64(6), object(5)
memory usage: 20.0+ KB


In [35]:
df['Embarked'].unique()

array(['C', 'S', 'Q'], dtype=object)

In [37]:
#One-hot encoding 'Embarked'

df = pd.get_dummies(df, columns=['Embarked'], prefix='Embarked')
df.head()

PassengerId Survived  Pclass  \
1             2      Yes       1   
3             4      Yes       1   
6             7       No       1   
10           11      Yes       3   
11           12      Yes       1   

                                                 Name  Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                             McCarthy, Mr. Timothy J    0  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                           Bonnell, Miss. Elizabeth    1  58.0      0   

    Parch    Ticket     Fare Cabin  Family Size  Embarked_C  Embarked_Q  \
1       0  PC 17599  71.2833   C85            2           1           0   
3       0    113803  53.1000  C123            2           0           0   
6       0     17463  51.8625   E46            1           0           0   
10      1   PP 9549  16.7000    G6            3           0           0   
11      0    113783  26.5500  C103            1           0           0   

    Embarked_S  
1            0  
3            1  
6            1  
10           1  
11           1